# Redmine plugin for OAuth
#
# Karel Pičman <karel.picman@kontron.com>
#
# This file is part of Redmine OAuth plugin.
#
# Redmine OAuth plugin is free software: you can redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# Redmine OAuth plugin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
# the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with Redmine OAuth plugin. If not, see
# <https://www.gnu.org/licenses/>.
#
# Rubocop configuration

AllCops:
  TargetRubyVersion: 3.2
  TargetRailsVersion: 7.1

  NewCops: enable

  Exclude:
    - '**/vendor/**/*'

plugins:
  - rubocop-performance
  - rubocop-rails

# Rules for OAuth
Layout/LineLength:
  Exclude:
    - lib/redmine_oauth/patches/account_controller_patch.rb
Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either
